# Generated by Django 2.2.12 on 2020-09-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='object_pk',
            field=models.UUIDField(verbose_name='object ID'),
        ),
    ]
