# Generated by Django 2.2.12 on 2020-09-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('meta_copyright', models.CharField(blank=True, max_length=255, verbose_name='Copyright')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos')),
                ('email', models.EmailField(help_text='This is required', max_length=254)),
                ('website', models.URLField(blank=True, help_text="Please start with 'https://www.'", null=True)),
                ('facebook', models.URLField(blank=True, help_text='Please leave empty if none', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Please leave empty if none', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Please leave empty if none', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Please leave empty if none', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Please leave empty if none', null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'biashara',
                'verbose_name_plural': 'biashara',
            },
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='business/photos')),
                ('alt', models.CharField(default='photo', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SameServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.Business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
