# Generated by Django 2.2.12 on 2020-10-11 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),
        ('business', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sameservices',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_sameservices_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='companysocialprofile',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='business.Business'),
        ),
        migrations.AddField(
            model_name='companysocialprofile',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Network'),
        ),
        migrations.AddField(
            model_name='businessimage',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='business.Business'),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Please leave empty if 100% virtual', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='business.SameServices', to='taggit.Tag', verbose_name='services'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
